name: CI Build

on:
  push:
    branches-ignore:
      - "releases/**"
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    strategy:
      matrix:
        qt_version: [5.12.11, 5.15.2]
        platform: [ubuntu-20.04, windows-latest, macos-latest]
        include:
          - platform: ubuntu-20.04
            make: make
            CXXFLAGS: -Wall -Wextra -pedantic
            MAKEFLAGS: -j2
          - platform: macos-latest
            make: make
            CXXFLAGS: -Wall -Wextra -pedantic -Wno-gnu-zero-variadic-macro-arguments # Ignore false-positive warning for qCWarning
            MAKEFLAGS: -j3
          - platform: windows-latest
            make: nmake
            CXXFLAGS: /W4 /WX /MP

    runs-on: ${{ matrix.platform }}
    env:
      CXXFLAGS: ${{ matrix.CXXFLAGS }}
      MAKEFLAGS: ${{ matrix.MAKEFLAGS }}

    steps:
      - name: Clone repo
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: ${{ matrix.qt_version }}

      - name: Setup MSVC environment for QMake
        uses: ilammy/msvc-dev-cmd@v1
 
      - name: Build with QMake
        run: |
          qmake CONFIG+=install_ok QT_PLATFORM=${{matrix.platform}} "QT_TOOL_PATH=${{steps.qt.outputs.qtdir}}/Tools" nut.pro

          ${{ matrix.make }} qmake_all
          ${{ matrix.make }}
