name: CI Build

on:
  push:
    branches-ignore:
      - "releases/**"
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        qt_version: [5.12.11, 5.15.2, 6.2.0]
        platform: [ubuntu-20.04, windows-latest, macos-latest]
        include:
          - qt_version: 6.2.0
            additional_arguments: -D QT_DEFAULT_MAJOR_VERSION=6
          - platform: ubuntu-20.04
            make: make
            #CXXFLAGS: -Wall -Wextra
            MAKEFLAGS: -j2
          - platform: macos-latest
            make: make
            #CXXFLAGS: -Wall -Wextra
            MAKEFLAGS: -j3
          - platform: windows-latest
            make: nmake
            CXXFLAGS: /Wall /Od
            QMAKE_MSC_VER: 16.11.31911.196

    runs-on: ${{ matrix.platform }}
    env:
      CXXFLAGS: ${{ matrix.CXXFLAGS }}
      MAKEFLAGS: ${{ matrix.MAKEFLAGS }}
      QMAKE_MSC_VER: ${{ matrix.QMAKE_MSC_VER }}
      CMAKE_PREFIX_PATH: $Qt6_DIR/lib/cmake

    steps:
      - name: Clone repo
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
          
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          version: ${{ matrix.qt_version }}

      - name: Setup MSVC environment for QMake
        uses: ilammy/msvc-dev-cmd@v1
        with:
          uwp: false
          
      - name: Build with QMake
        run: |
          qmake nut.pro
          ${{ matrix.make }} qmake_all
          ${{ matrix.make }}

      - name: Build with CMake
        if: startsWith(matrix.qt_version, '6.')
        run: |
          cmake . ${{ matrix.additional_arguments }}
          cmake --build .
  
